version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t helloworld:latest .
      - docker tag helloworld:latest 779155946353.dkr.ecr.eu-central-1.amazonaws.com/helloworld:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 779155946353.dkr.ecr.eu-central-1.amazonaws.com/helloworld:latest
